name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Tải File Hệ Thống
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/charan2004152004/Ngrok-Exe/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/nssm.exe -OutFile nssm.exe
        Invoke-WebRequest https://raw.githubusercontent.com/truyem789/blox-fruit/main/VegaX.rar -OutFile VegaX.rar
        Invoke-WebRequest https://raw.githubusercontent.com/truyem789/blox-fruit/main/wrar602.exe -OutFile wrar602.exe
        Invoke-WebRequest https://raw.githubusercontent.com/truyem789/blox-fruit/main/Roblox.exe -OutFile Roblox.exe
    - name: Copy Vào Thư Mục Máy Tính
      run: | 
        copy Roblox.exe C:\
        copy VegaX.rar C:\
        copy wrar602.exe C:\Users\
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download File Quan Trọng
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/loop.bat -OutFile loop.bat
    - name: Tạo tệp YML cho NGROK.
      run: start NGROK-US.bat
    - name: Bật quyền truy cập VPS
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tạo Tunnel
      run: sc start ngrok
    - name: Kết nối với VPS của bạn 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: Tất cả đã hoàn thành! Bạn có thể đóng tab luôn
      run: cmd /c loop.bat 
      
    
